# Generated by Django 4.0.4 on 2022-05-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_alter_ask_answer_alter_ask_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ask",
            name="answer",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="ask",
            name="status",
            field=models.TextField(default="initialized"),
        ),
    ]
