# Generated by Django 4.0.4 on 2022-05-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_ask_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_certificate',
            field=models.BooleanField(default=False),
        ),
    ]
